### ISSUE TITLE
Traceback from site: 'Expecting ',' delimiter: line 1 column 1631401 (char 1631400)'

### ISSUE THREAD

**Issue by pelson** [pelson/repohealth.info#14]
Hi,

I was looking at /report/pandas-dev/pandas on repohealth.info and got the following traceback:

```
Traceback (most recent call last):
  File "/app/repohealth/generate.py", line 63, in no_raise
    yield
  File "/app/repohealth/generate.py", line 263, in repo_data
    repo_data = json.load(fh)
  File "/app/.conda/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/app/.conda/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/app/.conda/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/app/.conda/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 1631401 (char 1631400)
```

Thanks,

**Comment by pelson** [comment]
As mentioned in https://github.com/pelson/repohealth.info/pull/13#issuecomment-275537475

**Comment by pelson** [comment]
Should be fixed by simplifying the issue handing callback. e951bacf7c66faed6f3873fb2f15f9149599d183...845ec60
