### ISSUE TITLE
Traceback from site: 'Expecting ',' delimiter: line 1 column 1951157 (char 1951156)'

### ISSUE THREAD

**Issue by pelson** [pelson/repohealth.info#17]
Hi,

I was looking at /report/numpy/numpy on repohealth.info and got the following traceback:

```
Traceback (most recent call last):
  File "/app/repohealth/generate.py", line 63, in no_raise
    yield
  File "/app/repohealth/generate.py", line 263, in repo_data
    repo_data = json.load(fh)
  File "/app/.conda/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/app/.conda/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/app/.conda/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/app/.conda/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 1951157 (char 1951156)
```

Direct link: https://repohealth.info/report/numpy/numpy

Thanks,

**Comment by pelson** [comment]
Relates to https://github.com/pelson/repohealth.info/issues/14. Though I thought this was fixed...

**Comment by pelson** [comment]
Hoping this is fixed in https://github.com/pelson/repohealth.info/commit/72fc5fa4d9c3ca104248608cb9e811ff8c0ea6a3#diff-0cbd5330a4d03075282e8c66aab6d744R20.
