### ISSUE TITLE
Traceback from site: 'HTTP 403: Forbidden'

### ISSUE THREAD

**Issue by jasperdj** [pelson/repohealth.info#18]
Hi,

I was looking at /report/spring-projects/spring-boot on repohealth.info and got the following traceback:

```
Traceback (most recent call last):
  File "/app/repohealth/generate.py", line 63, in no_raise
    yield
  File "/app/repohealth/generate.py", line 213, in repo_data
    stargazers = loop.run_sync(stargazers_fn)
  File "/app/.conda/lib/python3.5/site-packages/tornado/ioloop.py", line 457, in run_sync
    return future_cell[0].result()
  File "/app/.conda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/app/.conda/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/app/repohealth/github/stargazers.py", line 41, in repo_stargazers
    response = yield client.fetch(url, headers=headers)
  File "/app/.conda/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/app/.conda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
tornado.httpclient.HTTPError: HTTP 403: Forbidden
```

Direct link: https://repohealth.info/report/spring-projects/spring-boot

Thanks,

**Comment by pelson** [comment]
Curious. Today I'm able to access that link without any issue. As I recall, 403s were returned when I hit GitHub too hard with stargazer requests (as a result I capped the number of API calls). This is probably occurring because *other* repo requests have made substantial number of calls themselves (though not enough to hit the API rate limit).

There isn't an awful lot that can be done about this other than being a bit more defensive in the code (and potentially retrying in a few minutes).

I'd be interested to hear how frequently this ends up occurring, but for now, I'm probably not going to implement a fix right away. In terms of UI, perhaps it would be helpful to offer a retry button. Thoughts?

**Comment by pelson** [comment]
P.S. Thanks for reporting!
