### ISSUE TITLE
Traceback from site: ''

### ISSUE THREAD

**Issue by nimamotaharr** [pelson/repohealth.info#20]
Hi,

I was looking at /report/Microsoft/TypeScript on repohealth.info and got the following traceback:

```
Traceback (most recent call last):
  File "/app/.conda/lib/python3.5/site-packages/tornado/web.py", line 1469, in _execute
    result = yield result
  File "/app/.conda/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/app/.conda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/app/.conda/lib/python3.5/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/app/repohealth/webapp/handlers.py", line 127, in get
    if payload.get('status', 200) != 200:
AttributeError: 'NoneType' object has no attribute 'get'
```

Direct link: https://repohealth.info/report/Microsoft/TypeScript

Thanks,

**Comment by The-Compiler** [comment]
I got the same with qutebrowser/qutebrowser FWIW.
